server:
  port: 8001
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: servicehi
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"